hibernate:
    physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
    level:
        org:
            hibernate:
                type: trace
server:
    port: 9192
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        initialization-mode: always
        password: root
        url: jdbc:mysql://localhost:3306/test
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                format_sql: true
                show_sql: true